services:
  postgres:
    image: 'postgres:16'
    container_name: postgres-java
    environment:
      - POSTGRES_DB=taskflow
      - POSTGRES_USER=root
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=cheminov

  app:
    build: ./project
    container_name: app-java
    ports:
      - "8080:8080"